modLoader="javafml"
loaderVersion="[39,)"
license="All rights reserved"

[[mods]]
    modId="creeperoverhaul"
    version="${file.jarVersion}"
    displayName="Creeper Overhaul"
    logoFile="icon.png"
    authors="Artist/Creator - Joosh, Dev - ThatGravyBoat"
    description="Creeper overhaul adds a variety of different biome-specific creeper types to your world, some friendlier than others :)"

[[dependencies.creeperoverhaul]]
    modId="geckolib3"
    mandatory=true
    versionRange="[3.0.3,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.creeperoverhaul]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.creeperoverhaul]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
